# These credentials are used for dataporten, and is taken from the
# dataporten dashboard for your app. Leave unchanged if
# dataporten/feide is not to be used
OAUTH_CREDENTIALS = {
        'id': 'ClientID',
        'secret': 'ClientSecret'
}

# Key used for cookie signing. Can be generated by doing
# >>> import os
# >>> os.urandom(32)
# in an interactive python shell, and copying the resulting binary string
# directly
SECRET_KEY = '\x9aF\x07\xe6\x01\x02\xa1\xa8\xb2\xbb\x01\xfe\x9f\x0f\x81\xc9\xfd\x08\xf8]W\x8a^\t\xf5\xb9\x94$\xae\xae\xb3\xce'
